### ISSUE TITLE
Arrow keys to navigate do not work

### ISSUE THREAD

**Issue by hamishgraham** [Fakerr/git-recall#12]
System: macOS 10.12.1

I can run git-recall but I cannot move up and down the commit list with the arrow keys. The j/k keys do work correctly.

**Comment by Fakerr** [comment]
Thanks for reporting this. Apparently, there is an issue with arrow keys escape sequences in macOS. I'm working on a fix for it. :)

**Comment by Fakerr** [comment]
Added a fix for that but you will need to upgrade to bash 4.4.
