### ISSUE TITLE
sed: illegal option

### ISSUE THREAD

**Issue by hamishgraham** [Fakerr/git-recall#13]
System: macOS 10.12.1

When expanding one of the git commits with tab and closing it again the following error is shown:
```
sed: illegal option -- r various tweaks (3 days ago) <myname>
usage: sed script [-Ealn] [-i extension] [file ...] ago) <myname>
```

**Comment by henryk3dp** [comment]
Installing gnu-sed should fix that issue.

**Comment by milani** [comment]
`-E` has the same effect on OS X. So it can be easily replaced if the OS is not linux.
