### ISSUE TITLE
Expose `tig` in Prior Art section of README

### ISSUE THREAD

**Issue by lkraav** [Fakerr/git-recall#21]
As this is essentially a simpler version of https://github.com/jonas/tig, it would be for glorious benefit of all perhaps to have a Prior Art section, and tell people about this tool, too.

**Comment by henryk3dp** [comment]
The function of the README is to give a new user an introduction the to program and
give instructions on how to build, run and participate. It's a place to showcase this program, not other, unrelated but similar programs. 
While I also find tig to be a useful tool, I don't think the README should be used for anything but to showcase this particular project.
The exception would be to show a case where they can be used together to enhance the workflow, but this is not the case here.

**Comment by sethwklein** [comment]
In communities where it's common, I find projects that list other similar projects (perhaps with a note on differences) are usually better quality, and I look for that when evaluating projects.
