### ISSUE TITLE
Escape characters in diff view are not reproduced literally

### ISSUE THREAD

**Issue by LINKIWI** [Fakerr/git-recall#27]
Escape characters (at least newline `\n`) in the diff view of `git-recall` seem to be interpreted rather than echoed literally. It's easiest to show with an example:

Expected behavior (output of `git diff`):

```
-        char write_char = buf[write_len++];
+        const char write_char = buf[write_len++];
 
-        if (write_char == '\n') {
+        if (write_char == CHAR_LF) {
```

Actual behavior (using `git reacall`, after selecting a diff SHA and pressing enter):

```
-        char write_char = buf[write_len++];
+        const char write_char = buf[write_len++];
 
-        if (write_char == '
') {
+        if (write_char == CHAR_LF) {
```

This behavior occurs on `v1.1.2` (haven't used any earlier versions, so unsure if this is a regression or not).

**Comment by LINKIWI** [comment]
Seems like this could be caused by the `-e` option on `echo` at https://github.com/Fakerr/git-recall/blob/master/git-recall#L173

**Comment by Fakerr** [comment]
@LINKIWI Indeed, removing them will fix the issue. Thanks for reporting this :), I'll add fix.

**Comment by Fakerr** [comment]
Issue fixed.
