### ISSUE TITLE
Tab expansion not working

### ISSUE THREAD

**Issue by jadbox** [Fakerr/git-recall#29]
OS: Mac OS 10.11.6
Bash: 3.2.57
git-recall@1.1.5

Pressing tab on a commit only duplicates the 'commit row' below the line that I pressed tab upon.

Expected: Upon pressing tab, the expanded commit information should show below the current selected commit.

**Comment by Fakerr** [comment]
Hey, thanks for reporting the issue, I'm working on it. As a temporary workaround, you can use `e` key introduced in version 1.1.6 to reduce/expand the diff :)

**Comment by Fakerr** [comment]
It should work fine now.
