### ISSUE TITLE
Add option to disable line wrapping

### ISSUE THREAD

**Issue by rmorrin** [Fakerr/git-recall#31]
Hi there,

Is it possible to disable line wrapping on the log output? During my usage, I've found merge commits in particular have longer commit titles which are occasionally wrapping. This makes the log more difficult to read/navigate.

Fantastic tool, use this every day 👍

**Comment by Fakerr** [comment]
Hey @rmorrin, thanks for your contribution :)
I don't think it is possible right now to disable the line wrapping otherwise the logs will be messed up, but I'm thinking about excluding the merge commits from the logs (or maybe as option), so at least, you will have less wrapped lines.

**Comment by Fakerr** [comment]
Merge commits are now excluded from the log output. Maybe it will partially resolve your problem :+1: .
