### ISSUE TITLE
git recall for all users not working as expected

### ISSUE THREAD

**Issue by samaursa** [Fakerr/git-recall#4]
I expect `git recall -a "all"` to display what is shown in the `gif`. However, all I get is:

`The contributor ".*" did nothing during this period.

**Comment by Fakerr** [comment]
It means that during the last 24 hours, nothing happened. Try with the -d option. Something like this:
`git recall -a "all" -d 10`. to see for example the commits for the last 10 days.
I'll push a fix for the message to make it more clear. Thanks.

**Comment by samaursa** [comment]
Great. Yes a clearer message would work very well. Also, I think the default behavior, if number of days is not specified, is to show **n** number of commits. This can then replace `git log -n 10` for me.

**Comment by Fakerr** [comment]
Like the idea :+1: , I'll work on it. Thanks :)
