### ISSUE TITLE
git recall -a "my name" does not work

### ISSUE THREAD

**Issue by samaursa** [Fakerr/git-recall#5]
This may be related to the previous issue. But `git recall` is not working on my repository. You can checkout the repository here and try it:

https://github.com/samaursa/3LoC

**Comment by Fakerr** [comment]
Yeah, by default, only commits for the last 24 hours are displayed. you need to use the -d option.

**Comment by samaursa** [comment]
That makes sense and it does indeed work now.

Perhaps the default behavior should be to show **n** commits if # of days is not specified?
