### ISSUE TITLE
line break results in broken redraw

### ISSUE THREAD

**Issue by henryk3dp** [Fakerr/git-recall#6]
Hello,
if a line exceeds the terminal width, it results in the first line not being removed on redraw and piling up every time you move the cursor.
Tested on Debian Jessie (8.7)
ncurses 5.9
less 458
reproducible in both gnome-terminal and terminator

![git-recall_bug1](https://cloud.githubusercontent.com/assets/7522805/22407030/df863f8c-e65e-11e6-98c2-36d34982ea0b.png)

**Comment by Fakerr** [comment]
Indeed, there is a small bug. It should be easy to fix though. Thanks for reporting the issue, I'm working on it :) .

**Comment by gustavjorlov** [comment]
Seeing this issue as well. On macOS. If i make my terminal window wider than longest commit, the `j` and `k` movements work, but when pressing `tab` to open/close the code the code stays rendered even when closed.

**Comment by Fakerr** [comment]
Added a fix for this issue. (version 1.1.5)
cc @Teszko

**Comment by sigio** [comment]
Yup... works for me ;)
