### ISSUE TITLE
I get an abort error

### ISSUE THREAD

**Issue by CaptainJeff** [Fakerr/git-recall#8]
I installed it through npm but when i try to run git recall i get the following error

abort: the program lesskey is not installed. Make sure to install it before running git-recall

**Comment by lukasklein** [comment]
I assume you're on mac OS? Cause the same happened to me. Seems like `less` is compiled without the lesskey feature. I'm not sure how to fix it without recompiling less, though.

**Comment by G07cha** [comment]
I've got the same problem, for me, the solution was to install `less` from brew(which also includes `lesskey`):

```shell
brew install less
```

**Comment by lukasklein** [comment]
Did you install it from `dupes/less`?
```
> brew install less
Error: No available formula with the name "less"
==> Searching for similarly named formulae...
These similarly named formulae were found:
cless                                                               gitless                                                             lesspipe                                                            lesstif
To install one of them, run (for example):
  brew install cless
==> Searching taps...
These formulae were found in taps:
homebrew/dupes/less                                                 homebrew/science/bless                                              Caskroom/cask/endlesssky                                            Caskroom/cask/simpless
homebrew/emacs/less-css-mode                                        Caskroom/cask/charlessoft-timetracker                               Caskroom/cask/losslesscut                                           Caskroom/cask/wireless-transfer
To install one of them, run (for example):
  brew install homebrew/dupes/less
```

**Comment by G07cha** [comment]
Yes, to be more specific the command should be `brew install homebrew/dupes/less` as [Kevin said](https://github.com/Fakerr/git-recall/issues/3#issuecomment-272954245) in another issue. But similar search is performed automatically, therefore short name should work in most cases.

**Comment by Fakerr** [comment]
`Lesskey` is no longer required now.
